"""empty message

Revision ID: 904e6d238cb9
Revises: 37bca0ad3b92
Create Date: 2023-03-23 23:15:38.633374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904e6d238cb9'
down_revision = '37bca0ad3b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
